services:
  - type: web
    name: reword-this-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: gpt-3.5-turbo
      - key: MAX_TOKENS
        value: "1000"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PORT
        value: "10000"
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, X-Requested-With"
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://*.vercel.app https://*.render.com; img-src 'self' data: https:;" 